[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd smart-parking-backend && mvn clean package -DskipTests"]

[start]
cmd = "java -Xmx400m -Xms200m -XX:+UseSerialGC -jar smart-parking-backend/target/smart-parking-backend-1.0.0.jar"
